//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFacturas()
        {
            this.tbDetalleFacturas = new HashSet<tbDetalleFacturas>();
        }
    
        public int idFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public string idCliente { get; set; }
        public string tipoVenta { get; set; }
        public string tipoPago { get; set; }
        public bool estado { get; set; }
    
        public virtual tbClientes tbClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleFacturas> tbDetalleFacturas { get; set; }
        public virtual tbTipoPagos tbTipoPagos { get; set; }
        public virtual tbTipoVentas tbTipoVentas { get; set; }
    }
}
