//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string password { get; set; }
        public string rol { get; set; }
        public bool estado { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
