//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAutomovil
    {
        public int placa { get; set; }
        public string vin { get; set; }
        public int marca { get; set; }
        public int tipo { get; set; }
        public int color { get; set; }
        public bool estado { get; set; }
    
        public virtual tbColor tbColor { get; set; }
        public virtual tbMarca tbMarca { get; set; }
        public virtual tbTipoVehiculo tbTipoVehiculo { get; set; }
    }
}
