//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbExamen1POOEntities : DbContext
    {
        public dbExamen1POOEntities()
            : base("name=dbExamen1POOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAutomovil> tbAutomovil { get; set; }
        public virtual DbSet<tbColor> tbColor { get; set; }
        public virtual DbSet<tbMarca> tbMarca { get; set; }
        public virtual DbSet<tbTipoVehiculo> tbTipoVehiculo { get; set; }
    }
}
